### ISSUE TITLE
Inside Command Line

### ISSUE THREAD

**Issue by nizsheanez** [ostapetc/Yii-CMS-2.0#17]
1) On site page
2) On admin page
3) On exception page

**Comment by nizsheanez** [comment]
so much conditions in web interface. Go Using bash!
Won't realized

**Comment by ostapetc** [comment]
what are you talking about?)

**Comment by nizsheanez** [comment]
we have no bash language(conveyor, grep, sudo, ssh, streams redirecting, command history, and etc.), we have not interactive mode(without webSocket - may be you would implementing it?)

so, i think that it's cool feachure, but Putty or GitBush realy much sharper.

**Comment by ostapetc** [comment]
Putty, GitBush, grep, sudo, ssh - realy different things)))))))

**Comment by nizsheanez** [comment]
aaaa... what?

ok. for ex. you have your site on 2 servers. and whan you run comand from it command line, it command must be run on it server or on all servers?

**Comment by ostapetc** [comment]
depending on the task

**Comment by nizsheanez** [comment]
yes. 
and i think that from bash it doing simplify that from web interface. 
so, i don't see profit of using web shell.

**Comment by ostapetc** [comment]
одна из ситуаций. есть доступ только к репе, к серверу нет, а миграции накатить нужно

**Comment by ostapetc** [comment]
да и быстрее намного и удобнее накатить миграции через сайт нежели через ssh клиент, искать пароли итд

**Comment by nizsheanez** [comment]
Ну вообще согласен. если только для наката миграций - то сойдет.
Но полностью без интерактивности и прочих плюшек.
Могу вернуть если хочушь.
Как -то хотел еще его добавить на страницу эксэпшна, но там нет шаблона, в
общем какая-то была там проблема.

28 августа 2012 г., 14:51 пользователь ostapetc
notifications@github.comнаписал:

> да и быстрее намного и удобнее накатить миграции через сайт нежели через
> ssh клиент, искать пароли итд
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ostapetc/Yii-CMS-2.0/issues/17#issuecomment-8087738.

## 

Алексей Шаров

skype: nizsheanez
Tel.: +79252093945
e-mail: www.pismeco@gmail.com
http://freenews.kz

**Comment by ostapetc** [comment]
я думаю накат миграций мы визуальный в админке сделаем

28 августа 2012 г., 14:53 пользователь Alexey Sharov <
notifications@github.com> написал:

**Comment by nizsheanez** [comment]
Довольно странная мысль. Потому как причиной наката миграций в деве обычно
является - падение сайта.

28 августа 2012 г., 15:23 пользователь ostapetc
notifications@github.comнаписал:

> я думаю накат миграций мы визуальный в админке сделаем
> 
> 28 августа 2012 г., 14:53 пользователь Alexey Sharov <
> notifications@github.com> написал:
> 
> > Ну вообще согласен. если только для наката миграций - то сойдет.
> > Но полностью без интерактивности и прочих плюшек.
> > Могу вернуть если хочушь.
> > Как -то хотел еще его добавить на страницу эксэпшна, но там нет шаблона,
> > в
> > общем какая-то была там проблема.
> > 
> > 28 августа 2012 г., 14:51 пользователь ostapetc
> > notifications@github.comнаписал:
> > 
> > > да и быстрее намного и удобнее накатить миграции через сайт нежели
> > > через
> > > ssh клиент, искать пароли итд
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/ostapetc/Yii-CMS-2.0/issues/17#issuecomment-8087738>.
> > 
> > ## 
> > 
> > Алексей Шаров
> > 
> > skype: nizsheanez
> > Tel.: +79252093945
> > e-mail: www.pismeco@gmail.com
> > http://freenews.kz
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ostapetc/Yii-CMS-2.0/issues/17#issuecomment-8087779>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ostapetc/Yii-CMS-2.0/issues/17#issuecomment-8088371.

## 

Алексей Шаров

skype: nizsheanez
Tel.: +79252093945
e-mail: www.pismeco@gmail.com
http://freenews.kz
