### ISSUE TITLE
поломал iphone checkbox, посмотреть можно при авторизации

### ISSUE THREAD

**Issue by ostapetc** [ostapetc/Yii-CMS-2.0#40]

**Comment by nizsheanez** [comment]
Ага вижу. Посмотрю, может новую версию плагина вообще найду
Уууу! Зачетный фон. +5

**Comment by nizsheanez** [comment]
починил, Нашел другую проблему:
https://github.com/ostapetc/Yii-CMS-2.0/issues/42
