### ISSUE TITLE
посмотри плиз по верстке

### ISSUE THREAD

**Issue by ostapetc** [ostapetc/Yii-CMS-2.0#47]
когда находимся на клиенте в форме редактирования страницы .в визивике кликаем на иконку IMage и видим popup окно котором поехала верстка.  подумай что можно сделать чтобы на эту форму в popup не действовали стили

**Comment by nizsheanez** [comment]
я добавил стили для всплывающего окна - щас получше.
обновил elrte до версии 1.3
не работал файловый менеджер, я попытался обновить до версии 2.0Rc1 - настроить смог, но почему-то всплывающее окно не открывалось
пришлось откатиться до версии 1.2  - щас работает, но картинки тулбаре почему-то съехали. че-то сходу не получилось понять как же должно было быть. пока оставил как есть.

**Comment by nizsheanez** [comment]
Нашел еще клевую тему: https://github.com/ostapetc/Yii-CMS-2.0/issues/49
