### ISSUE TITLE
Просмотр альбома

### ISSUE THREAD

**Issue by yuri25** [ostapetc/Yii-CMS-2.0#66]
http://ptzw.ru.com/media/mediaAlbum/view/id/1

PHP warning

require(/..../ptzw.ru.com/protected/modules/Media/forms/UploadFilesForm.php): failed to open stream: No such file or directory

/..../ptzw.ru.com/protected/libs/yii/web/form/CFormElement.php(121)

**Comment by nizsheanez** [comment]
Fixed

**Comment by yuri25** [comment]
Переустановил все заново, миграции применил - пока все по прежнему...

http://ptzw.ru.com/media/mediaAlbum/view/id/1
PHP warning

require(/var/www/admin/data/www/ptzw.ru.com/protected/modules/Media/forms/UploadFilesForm.php): failed to open stream: No such file or directory

/..../ptzw.ru.com/protected/libs/yii/web/form/CFormElement.php(121)

**Comment by nizsheanez** [comment]
Пульнись еще раз, уже пофикшено.
