### ISSUE TITLE
Ошибка редактирования профиля

### ISSUE THREAD

**Issue by yuri25** [ostapetc/Yii-CMS-2.0#75]
PHP notice

Array to string conversion

/..../ptzw.ru.com/protected/libs/yii/db/CDbCommand.php(275)

**Comment by nizsheanez** [comment]
Не могу воспроизвести, можно ли побольше стек?

**Comment by yuri25** [comment]
Такое появляется только когда указываешь изображение к профилю, если без изображения то все нормально. 

PHP notice

Array to string conversion

/...../ptzw.ru.com/protected/libs/yii/db/CDbCommand.php(275)

Stack Trace
#5  –  /..../ptzw.ru.com/protected/components/ActiveRecord.php(477): CActiveRecord->findByPk("21", "", array())
.....
477         $result = parent::$method($pk, $condition, $params);
......

#6      –/...../ptzw.ru.com/protected/components/activeRecordBehaviors/UploadFileBehavior.php(60): ActiveRecord->findByPk("21")
......
60                         $object = $model->findByPk($model->id);
......
#12    –  /..../ptzw.ru.com/protected/modules/users/controllers/UserController.php(392): CActiveRecord->save()
.......
392         if ($form->submitted() && $user->save())
....

**Comment by nizsheanez** [comment]
Попробуй сделать пулл и накатить миграци

**Comment by nizsheanez** [comment]
fixed

**Comment by yuri25** [comment]
Знать бы что это такое:) Миграции я делал так, в консоли заходил в папку ....../protected и там выполнял 

 php yiic.php migrate  
Yii Migration Tool v1.0 (based on Yii v1.1.11)

extended with EMigrateCommand by cebe mail@cebe.cc

Total 2 new migrations to be applied:
    mailer: m120904_114039_insert_core_params
    core: m120926_124218_update_pages_types

Apply the above migrations? (yes|no) [no]:yes
**\* applying m120904_114039_insert_core_params
    > execute SQL ... done (time: 0.065s)
**\* applied m120904_114039_insert_core_params (time: 0.066s)

**\* applying m120926_124218_update_pages_types
    > execute SQL ... done (time: 0.021s)
**\* applied m120926_124218_update_pages_types (time: 0.022s)

Migrated up successfully.

Алексей, подскажи как сделать пулл и что это вообще такое. Прошу простить за тупость:)

**Comment by nizsheanez** [comment]
миграции сделал верно. 
пулл - это комманда git pull - которой ты забираешь изменения с гитхаба
похоже что ты все сделал верно, раз у тебя это вывелось. 
если все равно не заработает, сделай еще раз pull, я нашел в чем была проблема.

**Comment by yuri25** [comment]
Выполнил из корня сайта git pull - вроде все получилось, но теперь на главной CException

Не определено свойство "Page.image".

/.../ptzw.ru.com/protected/modules/content/models/Page.php(332)

**Comment by yuri25** [comment]
Попробую все снести и заново склонировать и установить

**Comment by yuri25** [comment]
Установка с нуля тоже неудачно, на втором шаге Yii Migration Tool v1.0 (based on Yii v1.1.11) extended with EMigrateCommand by cebe The following modules are disabled: core Current call is limited to module: users Total 7 new migrations to be applied: users: m120701_005441_users_create users: m120908_182118_create_test_user users: m120912_103643_set_name_default_value users: m120913_100323_alter_table_users_add_column_about_self users: m120913_140125_create_test2_user users: m120917_101223_users_generate_ten users: m121007_153730_create_user_parser **\* applying m120701_005441_users_create > execute SQL ... done (time: 0.000s) > execute SQL ... done (time: 0.074s) **\* applied m120701_005441_users_create (time: 0.076s) **\* applying m120908_182118_create_test_user

CDbCriteria#1
(
    [select] => '*'
    [distinct] => false
    [condition] => ''
    [params] => array()
    [limit] => -1
    [offset] => -1
    [order] => ''
    [group] => ''
    [join] => ''
    [having] => ''
    [with] => null
    [alias] => null
    [together] => null
    [index] => null
    [scopes] => null
    [CComponent:_e] => null
    [CComponent:_m] => null
)

**Comment by yuri25** [comment]
На миграции тоже стал ругаться:  PHP Fatal error:  require(): Failed opening required '/var/www/user/data/protected/config/constants.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/user/data/www/ptzw.ru.com/protected/yiic.php on line 23    Что то с путями, куда то папка www/ptzw.ru.com/   выпали....

**Comment by nizsheanez** [comment]
фигасе сколько всего :-) 
До вечера подниму.

**Comment by nizsheanez** [comment]
не сноси больше все :-) это только время у тебя будет отнимать. если что-то сломалось, то скорее всего оно просто сломалось, а не ты это поломал.

**Comment by nizsheanez** [comment]
починил миграции и главную страницу
