### ISSUE TITLE
Ошибка в конце установки

### ISSUE THREAD

**Issue by yuri25** [ostapetc/Yii-CMS-2.0#80]
Parse error: syntax error, unexpected '[', expecting ')' in /..../ptzw.ru.com/protected/modules/media/MediaModule.php on line 10

**Comment by nizsheanez** [comment]
ага! 
это мы на 5.4 переехали!
сори, но решили, что реальные пацаны не поддерживают обратную совместимость. 
насколько я знаю можно посадить 5.3 на 9000 порт, а 5.4 на 9054 например, сам не делал, но вроде можно. 
надо же когда-то двигаться вперед.

**Comment by yuri25** [comment]
Блин если я перейду на 5.4 то возможно с десяток сайтов у меня на сервере отвалится. Надо как то узнать можно ли для отдельных вируалхостов делать версию 5.4 а на других чтобы оставалась 5.3....А если нельзя - тогда тестировать только на localhost на open-server например.

**Comment by nizsheanez** [comment]
теоретически можно, например когда используешь nginx, то там явно в конфиге прописываешь порт на котором должен сидеть php-fpm 
но проблема в том, что 5.4 тянет за собой кучу зависимостей и не факт что эти зависимости в разных версиях сосуществуют позитивно. 
Могу дать контакт человека который настраивал себе для локального сайта доступ извне(через интренет)
https://github.com/sergeykondr
у него работает эта тема, я даже заходил
как сделал он подсказать не смогу, говорил что провайдер ему без вопросов дал IP

**Comment by yuri25** [comment]
Как там с ним связаться? Я что то не нашел никаких контактов с ним на Github, написал ему там в Issue но он не отвечает. Да и вряд ли получится держать на сервере 2 версии php... Поддержку спросил есть ли какое решение - так они сразу "к сожалению мы не производим установку php разных версий..." Жаль конечно, но попробую потестировать на Open-server на localhost.

**Comment by nizsheanez** [comment]
Он именно на локалке ставил. скайп: generalguderian

**Comment by yuri25** [comment]
Так а какой смысл ставить на локалке как то извращаясь если есть open-server.... просто чтобы извне заходить? И еще такой вопрос - разве между 5.3 и 5.4 такая огромная разница... ветка то одна. Попробую на open-server потестировать, хотя на реальном хостинге конечно было бы лучше.

**Comment by nizsheanez** [comment]
Разница не сверхбольшая, но она есть. Ты наверное заметил, что мы не пиаримся и не пишем open-source, поэтому нам не нужна обратная совместимость или что-то в этом духе. А раз не нужно поддерживать обратную совместимость, то нет смысла сидеть на старом ПО. Ну просто это не логично :-)
Так что извини, что лишнего гемора тебе добавил, но пока отступать не собираюсь :-)
