### ISSUE TITLE
Не подгружаются стили в date (FJuiDatePicker)

### ISSUE THREAD

**Issue by sergeykondr** [ostapetc/Yii-CMS-2.0#81]
там, где выбирается месяц, год, и календарь - отображается без стилей: http://s018.radikal.ru/i521/1210/38/5e1133eaa81a.jpg

**Comment by nizsheanez** [comment]
Пробовал чистить ассеты?

**Comment by sergeykondr** [comment]
пробовал, не помогает

**Comment by sergeykondr** [comment]
Вопрос снят. У меня не были скопированы css стили для jqueryUiThemes
