### ISSUE TITLE
Comment model has no method getUserId

### ISSUE THREAD

**Issue by yuri25** [ostapetc/Yii-CMS-2.0#89]
На локальном компе  win 7 - 64 open-server при попытке создать пост:
PHP notice

Undefined index: class

W:\domains\ostap\protected\modules\main\portlets\views\SidebarManager.php(13)

php 5.4.6

**Comment by yuri25** [comment]
Комментарии не добавляются, сообщение об ошибке всплывает в районе сайдбара и потом исчезает, скопировал что успел:

CException В классе Comment и его поведениях не найден метод или замыкание с именем "getUserId". (W:\domains\ostap\protected\libs\yii\base\CComponent.php:266)#0 W:\domains\ostap\protected\libs\yii\db\ar\CActiveRecord.php(226): CComponent->__call('getUserId', Array) #1 W:\domains\ostap\protected\modules\social\portlets\RatingPortlet.php(56): CActiveRecord->__call('getUserId', Array) #2 W:\domains\ostap\protected\modules\social\portlets\RatingPortlet.php(56): Comment->getUserId() #3 W:\domains\ostap\protected\libs\yii\zii\widgets\CPortlet.php(95): RatingPortlet->renderContent() #4 W:\domains\ostap\protected\libs\yii\web\CBaseController.php(174): CPortlet->run() #5 W:\domains\ostap\protected\components\Controller.php(258): CBaseController->widget('application.mod...', Array, false) #6 W:\domains\ostap\protected\modules\comments\views\comment_view.php(10): Controller->widget('application.mod...', Array) #7 W:\domains\ostap\protected\libs\yii\web\CBaseController.php(127): require('W:\domains\osta...') #8 W:\domains\ostap\protected\libs\yii\web\CBaseController.php(96): CBaseController->renderInternal('W:\domains\osta...', Array, true) #9 W:\domains\ostap\protected\libs\yii\web\CController.php(870): CBaseController->renderFile('W:\domains\osta...', Array, true) #10 W:\domains\ostap\protected\modules\comments\views\comment\list.php(2): CController->renderPartial('_view', Array) #11 W:\domains\ostap\protected\libs\yii\web\CBaseController.php(127): require('W:\domains\osta...') #12 W:\domains\ostap\protected\libs\yii\web\CBaseController.php(96): CBaseController->renderInternal('W:\domains\osta...', Array, true) #13 W:\domains\ostap\protected\libs\yii\

**Comment by nizsheanez** [comment]
Я думаю Артем разбрется. Правда, Артем? :-)

**Comment by nizsheanez** [comment]
fixed
