### ISSUE TITLE
Install + не найден объект User.role

### ISSUE THREAD

**Issue by djeklu** [ostapetc/Yii-CMS-2.0#97]
получается это на step2 когда модуль User пытается мигрировать
а именно видит этот файл: protected\modules\users\migrations\m121128_201845_create_admin_user.php
и пытается его выполнить

в нем чего то не хватает

пока решилась инсталяция методом удаления этого файла

а так же предлагаю добавить немного информативнее вывод об ошибках  - нет трассы:

а пока - так будет лучше видно где ошибка:
заменить (в protected\modules\install\InstallModule.php ):
                    $response = Yii::app()->executor->migrate('up --module='.$id);
                    if (stripos($response, 'successfully') === false)
                    {
                        echo $response;die;
                    }
на
                    $response = Yii::app()->executor->migrate('up --module='.$id);
                    if (stripos($response, 'successfully') === false)
                    {
                        echo Yii::getPathOfAlias($id.'.migrations')."<br>".$id."<br>".**FILE**.**LINE**.$response;die;
                    }

**Comment by nizsheanez** [comment]
А зачем выводить название файла и строку? 
Почему бы не выбросить исключение?

**Comment by djeklu** [comment]
это пример вывода подробной информации для поиска - кто же мне сообщил сообщение: "не найдет объект User.role"
никакой более подробной информации про ошибку не было нигде

**Comment by djeklu** [comment]
при регистрации нового пользователя в логах базы данных нашел такую ошибку:
exception 'CException' with message 'Не определено свойство "User.role".' in \www\cms2\protected\components\ActiveRecord.php:143
Stack trace:
#0 \www\cms2\protected\libs\yii\validators\CRangeValidator.php(50): ActiveRecord->__get('role')
#1 \www\cms2\protected\libs\yii\validators\CValidator.php(214): CRangeValidator->validateAttribute(Object(User), 'role')
#2 \www\cms2\protected\libs\yii\base\CModel.php(158): CValidator->validate(Object(User), NULL)

т.е. и все же - где то не хватает чего то
а именно
поля role (text) в таблице users
